  /*******************************************************************************
                              INICIO HOJA DE VIDA
  Fecha: 10/03/2016
  Autor: Omar Diaz Esquivel
  *******************************************************************************/

  /*::::: I DATOS PERSONALES DEL CANDIDATO :::::*/
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO CANDIDATO_APELLIDO_PATERNO, CAN.TX_AMATERNO CANDIDATO_APELLIDO_MATERNO, CAN.TX_NOMBRES CANDIDATO_NOMBRE_NOMBRES,
      TO_DATE(CAN.TX_FECHA_NAC,'YYYYMMDD') CANDIDATO_NACIMIENTO, (CASE TO_CHAR(CAN.ID_SEXO) WHEN '1' THEN 'MASCULINO' ELSE 'FEMENINO' END) CANDIDATO_SEXO,
      CAN.TX_PAIS NACIMIENTO_PAIS, UBI_NACIMIENTO.TXDEPARTAMENTO NACIMIENTO_DEPARTAMENTO, UBI_NACIMIENTO.TXPROVINCIA NACIMIENTO_PROVINCIA, UBI_NACIMIENTO.TXDISTRITO NACIMIENTO_DISTRITO,
      CAN.TX_PAIS_EXT_RES RESIDENCIA_PAIS, UBI_REDISENCIA.TXDEPARTAMENTO RESIDENCIA_DEPARTAMENTO, UBI_REDISENCIA.TXPROVINCIA RESIDENCIA_PROVINCIA, UBI_REDISENCIA.TXDISTRITO RESIDENCIA_DISTRITO, UPPER(CAN.TX_RESIDENCIA) RESIDENCIA_DIRECCION,
      UPPER(CAN.TX_CORREO) CANDIDATO_CORREO, TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, UPPER(CAN.TX_PORTAL_WEB) CANDIDATO_PORTAL_WEB, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
      DESIGNACION.TXNOMBRE CANDIDATO_FORMA_DESIGNACION
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP ID_ORG_POL AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_TIPO DESIGNACION ON CAN.ID_FORMA_DESIGNACION = DESIGNACION.IDTIPO AND DESIGNACION.IDCAMPO='DESIGNACION_CANDIDATURA' AND DESIGNACION.IDGRUPO=2 AND DESIGNACION.FGSITREG='A' AND DESIGNACION.IDTIPO<5
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
      LEFT JOIN  PADRON.UBIGEO UBI_NACIMIENTO ON UBI_NACIMIENTO.TXUBIGEO = CAN.ID_UBIGEO_NACIMIENTO
      LEFT JOIN  PADRON.UBIGEO UBI_REDISENCIA ON UBI_REDISENCIA.TXUBIGEO = CAN.ID_UBIGEO_RESIDENCIA
  WHERE CAN.ID_PROCESO_ELECTORAL = 79 --AND CAN.ID_CANDIDATO = 118115 
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO;


  /*::::: II EXPERIENCIA LABORAL :::::*/
  
  SELECT  CAN.ID_PROCESO_ELECTORAL ID_ELECCION, CAN.ID_CANDIDATO ID_CANDIDATO,
          CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO  || ' '  || CAN.TX_AMATERNO  || ' ' ||  CAN.TX_NOMBRES CANDIDATO_NOMBRE,
          --TRF_UBIGEOPROCESO.TXDEPARTAMENTO DEPARTAMENTO, TRF_UBIGEOPROCESO.TXPROVINCIA PROVINCIA, TRF_UBIGEOPROCESO.TXDISTRITO DISTRITO, TRF_UBIGEOPROCESO.TXUBIGEO,
          TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, 
          TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA, 
          (CASE CCP.ID_CONDICION WHEN 1 THEN 'DEPENDIENTE' ELSE 'INDEPENDIENTE' END) ELABORAL_CONDICION,
          UPPER(CCP.TX_EMPLEADOR) ELABORAL_CENTRO_TRABAJO, --CCP.TX_RUC,
          (CASE CCP.TX_UBIGEO_EXPERIENCIA WHEN '000000' THEN CCP.TX_PAIS ELSE UBI.TXDEPARTAMENTO || ' '  || UBI.TXPROVINCIA  || ' '  || UBI.TXDISTRITO END) ELABORAL_UBICACION,
          --CCP.TX_LUGAR_EXPERIENCIA DIRECCION_CENTRO_TRABAJO,
          UPPER(TSE.TX_NOMBRE_SECTOR) ELABORAL_SECTOR, CCP.TX_CARGO ELABORAL_CARGO, CCP.IN_INICIO_ANIO ELABORAL_ANIO_INICIO, CCP.IN_FIN_ANIO ELABORAL_ANIO_FIN,
          (CASE CCP.FG_HASTA_ACTUALIDAD WHEN '1' THEN 'SI' ELSE 'NO' END) ELABORAL_ACTUALIDAD
  FROM MSEGURIDAD.PECA_TBL_CANDIDATOEXPERIENCIA CCP
  INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATO CAN ON CAN.ID_CANDIDATO = CCP.ID_CANDIDATO AND CAN.ID_PROCESO_ELECTORAL = CCP.ID_PROCESO_ELECTORAL
  INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS  TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
  --INNER JOIN MSEGURIDAD.GENE_TRF_UBIGEOPROCESO TRF_UBIGEOPROCESO ON CAN.ID_UBIGEO_POSTULA = TRF_UBIGEOPROCESO.TXUBIGEO AND TRF_UBIGEOPROCESO.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
  LEFT JOIN PADRON.UBIGEO UBI ON CCP.TX_UBIGEO_EXPERIENCIA = UBI.TXUBIGEO 
  INNER JOIN MSEGURIDAD.PECA_TBL_TIPOSECTOR TSE ON TSE.ID_SECTOR = CCP.ID_SECTOR
  INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO
    ON CCP.ID_CANDIDATO=SIPE_TBL_CANDIDATO.IDCANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND CCP.ID_PROCESO_ELECTORAL=SIPE_TBL_CANDIDATO.IDPROCESO
  LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
  WHERE CCP.ID_PROCESO_ELECTORAL=79 AND CCP.FG_ESTADO = '1' --AND CAN.ID_CANDIDATO = 118102
  ORDER BY CCP.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO;

  /*::::: III FORMACIÓN ACADÉMICA :::::*/
  
  /* EDUCACION BASICA */  
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
      TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA, 
      TBL_EBASICA.TIPO EDUCACION_TIPO, UPPER(TBL_EBASICA.TX_CENTRO_PRIMARIA) EDUCACION_CENTRO,
      (CASE TBL_EBASICA.EDUBIGEO WHEN '000000' THEN  UPPER(TBL_EBASICA.TX_PAIS) ELSE UBI.TXDEPARTAMENTO || ' - ' || UBI.TXPROVINCIA || ' - ' || UBI.TXDISTRITO END) EDUCACION_UBICACION,
      TBL_EBASICA.ANIO_INICIO EDUCACION_ANIO_INICIO, TBL_EBASICA.ANIO_FIN EDUCACION_ANIO_FIN, TBL_EBASICA.GRADO_OBTENIDO EDUCACION_GRADO_OBTENIDO
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
      INNER JOIN (
        SELECT ID_PROCESO_ELECTORAL, ID_CANDIDATO, TX_CENTRO_PRIMARIA, TX_PAIS, TX_UBI_PRIMARIA EDUBIGEO, 'PRIMARIA' TIPO, 1 IDTIPO,
        (CASE IN_GRADO_I WHEN '1' THEN '1ERO ' END || CASE IN_GRADO_II WHEN '1' THEN '2DO ' END || CASE IN_GRADO_III WHEN '1' THEN '3ERO ' END || CASE IN_GRADO_IV WHEN '1' THEN '4TO ' END || CASE IN_GRADO_V WHEN '1' THEN '5TO ' END || CASE IN_GRADO_VI WHEN '1' THEN '6TO ' END) GRADO_OBTENIDO,
        NU_ANIO_INICIO_PRIMARIA ANIO_INICIO, NU_ANIO_FIN_PRIMARIA ANIO_FIN
        FROM MSEGURIDAD.PECA_TBL_CANDIDATOEDBASICA WHERE FG_PRIMARIA=1 AND NVL(FG_SECUNDARIA,0)=0 AND FG_ESTADO=1 AND ID_PROCESO_ELECTORAL = 79 
        UNION ALL
        SELECT ID_PROCESO_ELECTORAL, ID_CANDIDATO, TX_CENTRO_SECUNDARIA, TX_PAIS, TX_UBI_SECUNDARIA EDUBIGEO, 'SECUNDARIA' TIPO,  2 IDTIPO,
        (CASE IN_GRADO_I WHEN '1' THEN '1ERO ' END || CASE IN_GRADO_II WHEN '1' THEN '2DO ' END || CASE IN_GRADO_III WHEN '1' THEN '3ERO ' END || CASE IN_GRADO_IV WHEN '1' THEN '4TO ' END || CASE IN_GRADO_V WHEN '1' THEN '5TO ' END || CASE IN_GRADO_VI WHEN '1' THEN '6TO ' END) GRADO_OBTENIDO,
        NU_ANIO_INICIO_SECUNDARIA ANIO_INICIO, NU_ANIO_FIN_SECUNDARIA ANIO_FIN
        FROM MSEGURIDAD.PECA_TBL_CANDIDATOEDBASICA WHERE FG_SECUNDARIA=1 AND FG_ESTADO=1 AND ID_PROCESO_ELECTORAL = 79
      ) TBL_EBASICA ON CAN.ID_CANDIDATO = TBL_EBASICA.ID_CANDIDATO AND TBL_EBASICA.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
      LEFT JOIN PADRON.UBIGEO UBI ON TBL_EBASICA.EDUBIGEO = UBI.TXUBIGEO
  WHERE CAN.ID_PROCESO_ELECTORAL = 79 --AND CAN.ID_CANDIDATO = 118102 
  ORDER BY TBL_EBASICA.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO, TBL_EBASICA.IDTIPO, TBL_EBASICA.ANIO_FIN DESC;
  
  
  /* EDUCACION SUPERIOR */  
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
      TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA,
      TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
      TIPES.TX_TIPO_ESTUDIO EDUCACION_TIPO_ESTUDIO,
      (CASE TBL_ESUPERIOR.TX_UBIGEO_ESTUDIOS WHEN '000000' THEN  UPPER(TBL_ESUPERIOR.TX_PAIS) ELSE UBI.TXDEPARTAMENTO || ' - ' || UBI.TXPROVINCIA || ' - ' || UBI.TXDISTRITO END) EDUCACION_UBICACION,
      UPPER(TBL_ESUPERIOR.TX_NOMBRE_CARRERA) EDUCACION_CARRERA, UPPER(TBL_ESUPERIOR.TX_NOMBRE_ESTUDIO) EDUCACION_FACULTAD, UPPER(TBL_ESUPERIOR.TX_NOMBRE_CENTRO) EDUCACION_UNIVERSIDAD,
      UPPER(TBL_ESUPERIOR.TX_TIPO_GRADO) EDUCACION_GRADO_SUNEDU, TBL_ESUPERIOR.IN_ANIO_INICIO || ' - ' || TBL_ESUPERIOR.IN_ANIO_FINAL EDUCACION_PERIODO
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATOEDSUPERIOR TBL_ESUPERIOR ON CAN.ID_CANDIDATO = TBL_ESUPERIOR.ID_CANDIDATO AND TBL_ESUPERIOR.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL AND TBL_ESUPERIOR.FG_ESTADO = 1
      INNER JOIN MSEGURIDAD.PECA_TBL_TIPOESTUDIO TIPES ON TBL_ESUPERIOR.ID_TIPO_ESTUDIO = TIPES.ID_TIPO_ESTUDIO
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON 
        SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
      LEFT JOIN PADRON.UBIGEO UBI ON TBL_ESUPERIOR.TX_UBIGEO_ESTUDIOS = UBI.TXUBIGEO
  WHERE CAN.ID_PROCESO_ELECTORAL = 79 ---AND CAN.ID_CANDIDATO = 118102 
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO,TIPES.ID_TIPO_ESTUDIO, TBL_ESUPERIOR.IN_ANIO_FINAL DESC;
  
  /*::::: IV CARGOS PARTIDARIOS O DE ELECCIÓN POPULAR :::::*/

  /* A. CARGOS PARTIDARIOS */
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
      TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
      UPPER(CARGO_PARTI.TX_ORGANIZACION_POLITICA) CARGO_PARTI_ORGANIZACION, AMBITO.TX_AMBITO CARGO_PARTI_AMBITO,
      UPPER(CARGO_PARTI.TX_NOMBRE_CARGO) CARGO_PARTI_CARGO, 
      CARGO_PARTI.IN_ANIO_INICIO || ' - ' || CASE TO_CHAR(CARGO_PARTI.IN_ANIO_FINAL) WHEN '0' THEN 'HASTA LA ACTUALIDAD' ELSE TO_CHAR(CARGO_PARTI.IN_ANIO_FINAL) END CARGO_PARTI_PERIODO
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
      INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATOCARGOPARTI CARGO_PARTI ON CAN.ID_CANDIDATO = CARGO_PARTI.ID_CANDIDATO AND CARGO_PARTI.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL AND CARGO_PARTI.FG_ESTADO = 1 
      INNER JOIN MSEGURIDAD.GENE_TRF_AMBITO AMBITO ON CARGO_PARTI.ID_CIRCUNSCRIPCION = AMBITO.ID_AMBITO
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
  WHERE CAN.ID_PROCESO_ELECTORAL = 79 --AND CAN.ID_CANDIDATO = 118102 
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO;

  /*  B. CARGOS DE ELECCIÓN POPULAR */
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
      TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
      AMBITO.TX_AMBITO CARGO_POPUL_AMBITO, TIP_CARGO.TX_CARGO CARGO_POPUL_CARGO, UPPER(CARGO_POPUL.TX_PROCESO_ELECTORAL) CARGO_POPUL_PROCESO, 
      CARGO_POPUL.TX_ORGANIZACION_POLITICA CARGO_POPUL_ORGPOL, CARGO_POPUL.IN_ANIO_INICIO || ' - ' || CARGO_POPUL.IN_ANIO_FINAL CARGO_POPUL_PERIODO
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
      INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATOCARGOPOPUL CARGO_POPUL ON CAN.ID_CANDIDATO = CARGO_POPUL.ID_CANDIDATO AND CARGO_POPUL.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL AND CARGO_POPUL.FG_ESTADO = 1
      INNER JOIN MSEGURIDAD.GENE_TRF_AMBITO AMBITO ON CARGO_POPUL.ID_AMBITO = AMBITO.ID_AMBITO
      INNER JOIN  MSEGURIDAD.PECA_TBL_TIPOCARGO TIP_CARGO ON CARGO_POPUL.ID_CARGO = TIP_CARGO.ID_CARGO
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
      WHERE CAN.ID_PROCESO_ELECTORAL = 79 --AND CAN.ID_CANDIDATO = 118126 
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO;

  /*  C. INFORMACIÓN ADICIONAL O COMPLEMENTARIA */

  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
      TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
      UPPER(ADICIONAL.TX_INSTITUCION) ADICIONAL_ENTIDAD, UPPER(ADICIONAL.TX_CARGO) ADICIONAL_CARGO, 
      ADICIONAL.IN_ANIO_INICIO || ' - ' || ADICIONAL.IN_ANIO_FINAL ADICIONAL_PERIODO
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
      INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATOADICIONAL ADICIONAL ON CAN.ID_CANDIDATO = ADICIONAL.ID_CANDIDATO AND ADICIONAL.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL AND ADICIONAL.FG_ESTADO = 1
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
  WHERE CAN.ID_PROCESO_ELECTORAL = 79 --AND CAN.ID_CANDIDATO = 118126 
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO, ADICIONAL.IN_ANIO_FINAL DESC;

  /*::::: V MENCIÓN DE RENUNCIAS :::::*/
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
      TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
      UPPER(RENUNCIA.TX_ORG_POLITICA) RENUNCIA_ORGPOL, RENUNCIA.IN_ANIO_INICIO RENUNCIA_AFILIACION,
      RENUNCIA.IN_ANIO_FINAL RENUNCIA_DESAFILICACION
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
      INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATORENUNCIASOP RENUNCIA ON CAN.ID_CANDIDATO = RENUNCIA.ID_CANDIDATO AND RENUNCIA.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL AND RENUNCIA.FG_ESTADO = 1    
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
  WHERE CAN.ID_PROCESO_ELECTORAL = 79 --AND CAN.ID_CANDIDATO = 118102 
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO;

  /*::::: VI RELACIÓN DE SENTENCIAS :::::*/ 
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
      TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
      SENTENCIA.TX_EXPEDIENTE SENTENCIA_EXPEDIENTE, TO_DATE(SENTENCIA.TX_FECHA_SENTENCIA,'DDMMYYYY') SENTENCIA_FECHA, UPPER(SENTENCIA.TX_JUZGADO) SENTENCIA_JUZGADO,
      UPPER(SENTENCIA.TX_ACUSACION_PENAL) SENTENCIA_DELITO, UPPER(SENTENCIA.TX_FALLO) SENTENCIA_FALLO, UPPER(SENTENCIA.TX_MODALIDAD) SENTENCIA_MODALIDAD, 
      UPPER(SENTENCIA.TX_CUMPLIMIENTOFALLO) SENTENCIA_CUMPLIMIENTO, UPPER(SENTENCIA.TX_OBLIGACIONREPARACION) SENTENCIA_OBLIGA_REPARACION,
      UPPER(SENTENCIA.TX_PAGOREPARACION) SENTENCIA_PAGO
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATOAMBITOPENA SENTENCIA ON CAN.ID_CANDIDATO = SENTENCIA.ID_CANDIDATO AND SENTENCIA.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL AND SENTENCIA.FG_ESTADO = 1
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
  WHERE CAN.ID_PROCESO_ELECTORAL = 79 --AND CAN.ID_CANDIDATO = 118130 
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO, SENTENCIA_FECHA DESC;

  /*::::: VII RELACIÓN DE SENTENCIAS QUE DECLAREN FUNDADAS LAS DEMANDAS INTERPUESTAS CONTRA LOS CANDIDATOS(AS) POR INCUMPLIMIENTO DE OBLIGACIONES ALIMENTARIAS, CONTRACTUALES, LABORALES O POR INCURRIR EN VIOLENCIA FAMILIAR, QUE HUBIERAN QUEDADO FIRMES. :::::*/ 
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
    CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
    TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
    SENTENCIA.TX_EXPEDIENTE SENTENCIA_EXPEDIENTE, UPPER(SENTENCIA.TX_JUZGADO) SENTENCIA_JUZGADO, 
    UPPER(SENTENCIA.TX_MATERIA) SENTENCIA_MATERIA_DEMANDA, UPPER(SENTENCIA.TX_FALLO) SENTENCIA_FALLO
    FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
    INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
    INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATOAMBITOCIVI SENTENCIA ON CAN.ID_CANDIDATO = SENTENCIA.ID_CANDIDATO AND SENTENCIA.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL AND SENTENCIA.FG_ESTADO = 1
    INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
    LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
    WHERE CAN.ID_PROCESO_ELECTORAL = 79 --AND CAN.ID_CANDIDATO = 118126 
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO;

  /*::::: VIII DECLARACIÓN JURADA DE INGRESOS DE BIENES Y RENTAS :::::*/
  
  /* INGRESOS*/
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
      TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
      TO_NUMBER(INGRESO.TX_REMUNERACION_PUBLICO) INGRESO_REMUNERACION_PUBLICO, INGRESO.TX_REMUNERACION_PRIVADO INGRESO_REMUNERACION_PRIVADO, INGRESO.TX_REMUNERACION_TOTAL INGRESO_REMUNERACION_TOTAL,
      INGRESO.TX_RENTA_PUBLICO INGRESO_RENTA_PUBLICO, INGRESO.TX_RENTA_PRIVADO INGRESO_RENTA_PRIVADO, INGRESO.TX_RENTA_TOTAL INGRESO_RENTA_TOTAL,
      INGRESO.TX_OTROS_PUBLICO INGRESO_OTROS_PUBLICO, INGRESO.TX_OTROS_PRIVADO INGRESO_OTROS_PRIVADO, INGRESO.TX_OTROS_TOTAL INGRESO_OTROS_TOTAL
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
      INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATOINGRESOS INGRESO ON CAN.ID_CANDIDATO = INGRESO.ID_CANDIDATO AND INGRESO.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL 
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
      WHERE CAN.ID_PROCESO_ELECTORAL = 79 --AND CAN.ID_CANDIDATO = 118101 
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO;

  /* BIENES INMUEBLES DEL DECLARANTE Y SOCIEDAD DE GANANCIALES (país o extranjero) */
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
      TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
      UPPER(BIENES.TX_NOMBRE_BIEN) BIEN_TIPO, UPPER(BIENES.TX_DESCRIPCION_BIEN) BIEN_DIRECCION, 
      BIENES.TX_CARACTERISTICAS_BIEN BIEN_REG_PUBLICO, BIENES.TX_VALOR_BIEN BIEN_VALOR
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
      INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATOBIENES BIENES ON CAN.ID_CANDIDATO = BIENES.ID_CANDIDATO AND BIENES.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL AND BIENES.ID_BIEN = 1 AND BIENES.FG_ESTADO = 1 
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
  WHERE CAN.ID_PROCESO_ELECTORAL = 79 --AND CAN.ID_CANDIDATO = 118126 
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO;

  /* BIENES MUEBLES DEL DECLARANTE Y SOCIEDAD GANANCIALES (país o extranjero) */
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
      TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
      UPPER(BIENES.TX_NOMBRE_BIEN) BIEN_VEHICULO, UPPER(BIENES.TX_DESCRIPCION_BIEN) BIEN_MARCA_MODELO_ANIO, 
      BIENES.TX_CARACTERISTICAS_BIEN BIEN_PLACA_CARACTERISTICAS, BIENES.TX_VALOR_BIEN BIEN_VALOR
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
      INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATOBIENES BIENES ON CAN.ID_CANDIDATO = BIENES.ID_CANDIDATO AND BIENES.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL AND BIENES.ID_BIEN = 2 AND BIENES.FG_ESTADO = 1 
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
  WHERE CAN.ID_PROCESO_ELECTORAL = 79 --AND CAN.ID_CANDIDATO = 118126 
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO;

  /* OTROS */
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
      TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
      UPPER(BIENES.TX_NOMBRE_BIEN) BIEN_OTRO, UPPER(BIENES.TX_DESCRIPCION_BIEN) BIEN_DESCRIPCION, 
      UPPER(BIENES.TX_CARACTERISTICAS_BIEN) BIEN_CARACTERISTICAS, BIENES.TX_VALOR_BIEN BIEN_VALOR
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
      INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATOBIENES BIENES ON CAN.ID_CANDIDATO = BIENES.ID_CANDIDATO AND BIENES.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL AND BIENES.ID_BIEN = 3 AND BIENES.FG_ESTADO = 1 
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
  WHERE CAN.ID_PROCESO_ELECTORAL = 79 --AND CAN.ID_CANDIDATO = 118094 
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO;

  /* ACREENCIAS Y OBLIGACIONES A SU CARGO */
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
      TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
      UPPER(ACREENCIA.TX_DETALLE_ACREENCIA) ACREENCIA_DETALLE, ACREENCIA.TX_TOTAL_DEUDA ACREENCIA_MONTO
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
      INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATOEGRESOS ACREENCIA ON CAN.ID_CANDIDATO = ACREENCIA.ID_CANDIDATO AND ACREENCIA.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL AND ACREENCIA.FG_ESTADO = 1
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
  WHERE CAN.ID_PROCESO_ELECTORAL = 79 --AND CAN.ID_CANDIDATO = 118126 
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO;

  /*::::: IX INFORMACIÓN ADICIONAL(Opcional) :::::*/
  
  /* INFORMACIÓN ADICIONAL */
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
      TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
      UPPER(ADICIONAL.TX_MATERIA) ADICIONAL_MATERIA, ADICIONAL.TX_EXPEDIENTE ADICIONAL_EXPEDIENTE, 
      UPPER(ADICIONAL.TX_JUZGADO) ADICIONAL_JUZGADO, UPPER(ADICIONAL.TX_ESTADOACTUAL) ADICIONAL_ESTADO
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
      INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATOINFADI ADICIONAL ON CAN.ID_CANDIDATO = ADICIONAL.ID_CANDIDATO AND ADICIONAL.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL AND ADICIONAL.FG_TIPOINFORMACION=0 AND ADICIONAL.FG_ESTADO=1
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
  WHERE CAN.ID_PROCESO_ELECTORAL = 79 AND ADICIONAL.TX_MATERIA IS NOT NULL --AND CAN.ID_CANDIDATO = 118102
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO;

  /* INFORMACIÓN QUE CONSIDERÓ QUE LA CIUDADANÍA DEBA CONOCER */
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
      TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
      UPPER(ADICIONAL.TX_INFORMACION) ADICIONAL_INFORMACION
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
      INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATOINFADI ADICIONAL ON CAN.ID_CANDIDATO = ADICIONAL.ID_CANDIDATO AND ADICIONAL.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL AND ADICIONAL.FG_TIPOINFORMACION=1 AND ADICIONAL.FG_ESTADO=1
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
  WHERE CAN.ID_PROCESO_ELECTORAL = 79 AND ADICIONAL.TX_INFORMACION IS NOT NULL --AND CAN.ID_CANDIDATO = 118103
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO;

  /*::::: X OBSERVACIONES INGRESADAS :::::*/
  SELECT CAN.ID_PROCESO_ELECTORAL ID_ELECCION,
      CAN.ID_CANDIDATO ID_CANDIDATO, CAN.TX_DNI CANDIDATO_DNI, CAN.TX_APATERNO || ' ' || CAN.TX_AMATERNO || ' ' || CAN.TX_NOMBRES AS CANDIDATO_NOMBRE,
      TBL_OPINSCRITAS.COD_OP ID_ORG_POLITICA, TBL_OPINSCRITAS.DES_OP CANDIDATO_ORG_POLITICA, TRF_CARGO_AUTORIDAD.TXCARGOAUTORIDAD CANDIDATO_CARGO_POSTULA,
      ANOTACION.TXREFERENCIA ANOTACION_REFERENCIA, UPPER(LTRIM(REPLACE(Regexp_Replace(ANOTACION.TXOBSERVACION, '<[^>]*>|(&nbsp;)','\1 '), Chr(13)||Chr(10)))) ANOTACION_MARGINAL
      FROM MSEGURIDAD.PECA_TBL_CANDIDATO CAN    
      INNER JOIN MSEGURIDAD.GENE_TBL_OPINSCRITAS TBL_OPINSCRITAS ON CAN.ID_ORG_POL = TBL_OPINSCRITAS.COD_OP AND TBL_OPINSCRITAS.IDPROCESO=CAN.ID_PROCESO_ELECTORAL
      INNER JOIN MSEGURIDAD.PECA_TBL_CANDIDATOANOTMARGINAL ANOTACION ON CAN.ID_CANDIDATO = ANOTACION.ID_CANDIDATO AND ANOTACION.ID_PROCESO_ELECTORAL = CAN.ID_PROCESO_ELECTORAL    
      INNER JOIN SIPESGERM2010.SIPE_TBL_CANDIDATO SIPE_TBL_CANDIDATO ON SIPE_TBL_CANDIDATO.IDCANDIDATO = CAN.ID_CANDIDATO AND SIPE_TBL_CANDIDATO.FGSITREG = 'A' AND SIPE_TBL_CANDIDATO.IDPROCESO = CAN.ID_PROCESO_ELECTORAL
      LEFT JOIN  MSEGURIDAD.GENE_TRF_CARGOAUTORIDAD TRF_CARGO_AUTORIDAD ON SIPE_TBL_CANDIDATO.IDCARGO = TRF_CARGO_AUTORIDAD.IDCARGOAUTORIDAD
  WHERE CAN.ID_PROCESO_ELECTORAL = 79 --AND CAN.ID_CANDIDATO = 118094 
  ORDER BY CAN.ID_CANDIDATO, SIPE_TBL_CANDIDATO.IDCARGO;

  /*******************************************************************************
                              FIN HOJA DE VIDA
  *******************************************************************************/







