### Hojas de Vida 2020

```{r}
library(rio)

ece20 <- import_list('Hojas de Vida ECE2020.xlsx',rbind=FALSE)
```


```{r}
names(ece20)
```

```{r}
ece20=ece20[c(-c(3,6:11))]
```

```{r}
names(ece20)=c("EduBAS","EduTEC","EduUNI","EduPOST")
```



```{r}
names(ece20$EduBAS)
```

```{r}
ece20$EduBAS= ece20$EduBAS[,-c(2:4,6,8:10)]
names(ece20$EduBAS)
```

```{r}
Prim=ece20$EduBAS[ece20$EduBAS$TXCONCLUYOPRIMARIA=="SI",c(1,2)]
Prim=Prim[!duplicated(Prim$IDHOJAVIDA),]
Prim=Prim[complete.cases(Prim),]
names(Prim)[2]='tienePrimaria'
```

```{r}
Secu=ece20$EduBAS[ece20$EduBAS$TXCONCLUYOSECUNDARIA=="SI",c(1,3)]
Secu=Secu[!duplicated(Secu$IDHOJAVIDA),]
Secu=Secu[complete.cases(Secu),]
names(Secu)[2]='tieneSecundaria'
```

names(ece20$EduTEC)
```{r}
Tecs=ece20$EduTEC[ece20$EduTEC$TXCONCLUYO=="SI",c(1,3,5)]
Tecs=Tecs[!duplicated(Tecs$IDHOJAVIDA),]
Tecs=Tecs[complete.cases(Tecs),]
names(Tecs)[2]='tieneTec'
```

####
```{r}
Bachis=ece20$EduUNI[ece20$EduUNI$TXBACHILLER=="SI",c("IDHOJAVIDA","TXBACHILLER","TXANIOBACHILLER","TXUNIVERSIDAD")]
Bachis=Bachis[complete.cases(Bachis),]
Bachis=Bachis[!duplicated(Bachis$IDHOJAVIDA),]
names(Bachis)[2:4]=c('tieneBach','FechaBach','UniBach')
```


```{r}
Lics=ece20$EduUNI[ece20$EduUNI$TXTITULO=="SI",c("IDHOJAVIDA","TXTITULO","TXANIOTITULO")]
Lics=Lics[complete.cases(Lics),]
Lics=Lics[!duplicated(Lics$IDHOJAVIDA),]
names(Lics)[2:3]=c('tieneTit','FechaTit')
```

```{r}
Magis=ece20$EduPOST[ece20$EduPOST$TXGRADO=='MAESTRO' & ece20$EduPOST$FGTENGOPOSGRADO==1,c(7,2,3)]
Magis=Magis[complete.cases(Magis),]
Magis=Magis[!duplicated(Magis$IDHOJAVIDA),]
names(Magis)[2:3]=c('tieneMAG','UniMAG')
```

```{r}
Doct=ece20$EduPOST[ece20$EduPOST$TXGRADO=='DOCTOR' & ece20$EduPOST$FGTENGOPOSGRADO==1,c(7,2,3)]
Doct=Doct[complete.cases(Doct),]
Doct=Doct[!duplicated(Doct$IDHOJAVIDA),]
names(Doct)[2:3]=c('tieneDOC','UniDOC')
```


```{r}

library(readxl)
DataOfi =read_excel("Datos Candidatos ECE2020.xlsx")
names(DataOfi)
```


```{r}
names(DataOfi)[1]='IDHOJAVIDA'
DataOfi$IDHOJAVIDA...11=NULL

```

```{r}
PerfilACA=base::merge(DataOfi,Prim,all.x=T)
PerfilACA=base::merge(PerfilACA,Secu,all.x=T)
PerfilACA=base::merge(PerfilACA,Tecs,all.x=T)
PerfilACA=base::merge(PerfilACA,Bachis,all.x=T)
PerfilACA=base::merge(PerfilACA,Lics,all.x=T)
PerfilACA=base::merge(PerfilACA,Magis,all.x=T)
PerfilACA=base::merge(PerfilACA,Doct,all.x=T)
```

```{r}
PerfilACA$joven=ifelse(PerfilACA$NUEDAD>30,0,1)
```

```{r}
names(PerfilACA)
```

```{r}
PerfilACA=PerfilACA[,c(1:17,19,22,24,26,18,20,21,23,25,27,28)]
```

```{r}

PerfilACA[,c(15:21)][is.na(PerfilACA[,c(15:21)])] = 0
PerfilACA[,c(15:21)][PerfilACA[,c(15:21)]=='SI'] = 1
PerfilACA[,c(15:21)]=lapply(PerfilACA[,c(15:21)],as.numeric)
```

```{r}
PerfilACA$nivelACAD=apply(PerfilACA[,c(15:21)],1,sum)
```
```{r}
write.csv(PerfilACA,"PerfilACA.csv",row.names = F)
```

